baseurl = "https://finnkauski.com"
languageCode = "en-us"
theme = "m10c"
paginate = 5
googleAnalytics = "UA-150010764-1"

[markup]
  math=true
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
  author = "Art Eidukas"
  avatar = "https://i.imgur.com/udYAc6d.jpg"

[[params.social]]
  name = "github"
  url = "https://github.com/finnkauski"

[[params.social]]
  name = "keybase"
  url = "https://keybase.io/finnkauski"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  primaryColor = "#ffffff"
  lightColor = "#a2a2a2"
  lightestColor = "#d3d3d3"

[languages]
  [languages.en]
    languageName = "English"
    title = "the.finest.art"
    description = "Just making stuff and sharing what I learn."
